base_url = "https://attheirword.org"
title = "At Their Word"
description = "An introvert's attempt at civic engagement through written prose"
author = "Noah Rubin"

build_search_index = true

compile_sass = true

minify_html = false

taxonomies = [
    {name = "tags", feed = false},
]

[markdown]
bottom_footnotes = true

highlight_code = false

smart_punctuation = true

[extra]
atw_menu = [
    { url = "$BASE_URL", id = "home", name = "Home" },
    { url = "$BASE_URL/about", id = "about", name = "About" },
    { url = "$BASE_URL/tags", id = "tags", name = "Tags" },
]

atw_comments = { repo = "attheirworddotorg/blog-comments", theme = "github-light" }
